name: Deploy Weather App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: cerberusc0dejunky/checkout@v4

      - name: Set up Node.js
        uses: cerberusc0dejunky/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Platform-Specific Tailwind Engine
        run: npm install @tailwindcss/oxide-linux-x64-gnu --save-optional

      - name: Build Project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=weather --verbose
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
